
FROM postgres

RUN usermod -u 60005 postgres
RUN groupmod -g 60005 postgres

COPY ./backup_all_weather_postgres.dump /tmp/backup.dump
COPY ./restore.sh /docker-entrypoint-initdb.d/restore.sh
RUN chmod +x /docker-entrypoint-initdb.d/restore.sh

#RUN pg_restore -U user -d cnmost -v /tmp/backup.dump
